### ISSUE TITLE
Errors in parsing version JSON file

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/java-representer#104]
We're getting the following error in production:

```
unexpected characters after the JSON document (after ) at line 2, column 1 [parse.c:731] in '{"version": 1} {"version": 1} {"version": 1} {"version": 1}
```

**Comment by ErikSchierboom** [comment]
The newline was not the issue, the issue is that there are two objects being written:

```
# cat representation.json 
{"version": 1}{"version": 1}
```

**Comment by sanderploegsma** [comment]
Huh, that is strange! Does this happen every time or only for certain exercises?

And I assume the error in the OP says that it actually contained four objects?

**Comment by sanderploegsma** [comment]
Ah, I see where this is going wrong: if I change one of the smoke tests to contain more than one solution file it prints the version twice...

**Comment by ErikSchierboom** [comment]
Aha!
