### ISSUE TITLE
Build and push docker image error

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java-representer#21]
Failure during the step `Build and push Docker image`

with this message
`buildx call failed with: failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed`

**Comment by mirkoperillo** [comment]
Hi @ErikSchierboom do you have any idea about ?

**Comment by ErikSchierboom** [comment]
@mirkoperillo I do :) The very first time a Docker image is pushed for a tooling image (representer/analyzer/test runner), I need to do that manually and set some permissions at Docker hub. I've just done this, so this should be fixed now. You can check this by re-running the Docker workflow (I don't have permissions to do that).

**Comment by mirkoperillo** [comment]
Thank you @ErikSchierboom, now the error is changed.
No more a permission issue, but

```
failed to solve: rpc error: code = Unknown desc = unexpected status: 404 Not Found
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = unexpected status: 404 Not Found
```

Did you ever see something like this ?

**Comment by ErikSchierboom** [comment]
@mirkoperillo Ah yes, that is the second Docker repo :) I've created a PR to add it to our production deploy: https://github.com/exercism/terraform/pull/21 Once @iHiD has merged that, this error should be fixed.

**Comment by mirkoperillo** [comment]
thank you,  I leave this issue opened waiting for the merge

**Comment by iHiD** [comment]
Done.

**Comment by mirkoperillo** [comment]
Everything alright, thank you, I can close this issue
